config/routes.rb
require 'sidekiq/web'
Infobase::Application.routes.draw do
  get "gcx_site_users/new"

  get "gcx_site_users/create"

  resources :gcx_sites
  resources :gcx_site_users

  namespace :api, defaults: {format: 'json'} do
    api_version(module: 'V1', header: {name: 'API-VERSION', value: 'v1'}, parameter: {name: "version", value: 'v1'}, path: {value: 'v1'}) do
      resources :ministries
      resources :regions
      resources :teams do
        collection do
          post :search # This is needed for searches with lots of parameters
        end
      end
      resources :target_areas
      resources :users
      resources :activities
      resources :strategies
      resources :people

      resources :statistics do
        collection do
          get :activity
          get :sp_evangelism_combined
          post :collate_stats
          post :collate_stats_intervals
          post :movement_stages
        end
      end

      resources :people do
        collection do
          get :is_staff
          post :is_staff
        end
      end
    end
  end

  resources :infobase_report_rows

  resources :teams do
    collection do
      get :search
      get :search_results
      post :search_results
      get :region
      get :state
      get :ministry
    end
    member do
      post :add_member
      delete :remove_member
      get :search_members
      post :search_members_results
      get :new_member
      post :create_member
      post :add_leader
      post :remove_leader
    end
  end
  get 'teams/validate/:name' => 'teams#validate_name'
  get 'locations/validate/:name' => 'locations#validate_name'
  get 'teams/region/:region/state/:state/city/:city' => 'teams#city', :as => :team_city, :constraints => {:city => /.+/}
  get 'teams/region/:region/state/:state/:all' => 'teams#state', :as => :team_state_all
  get 'teams/region/:region/state/:state' => 'teams#state', :as => :team_state
  get 'teams/region/:region/country/:country/city/:city' => 'teams#city', :as => :team_country_city, :constraints => {:city => /.+/}
  get 'teams/region/:region/country/:country/:all' => 'teams#country', :as => :team_country_all
  get 'teams/region/:region/country/:country' => 'teams#country', :as => :team_country
  get 'teams/region/:region/:all' => 'teams#region', :as => :team_region_all
  get 'teams/region/:region' => 'teams#region', :as => :team_region
  get 'teams/ministry/:strategy' => 'teams#ministry', :as => :team_ministry
  post 'teams/:id/add_member/:person_id' => 'teams#add_member', :as => :team_add_member
  delete 'teams/:id/remove_member/:person_id' => 'teams#remove_member', :as => :team_remove_member
  post 'teams/:id/add_leader/:person_id' => 'teams#add_leader', :as => :team_add_leader
  post 'teams/:id/remove_leader/:person_id' => 'teams#remove_leader', :as => :team_remove_leader

  resources :locations do
    resources :movements do
      member do
        post :add_contact
        delete :remove_contact
        get :search_contacts
        post :search_contacts_results
        get :new_contact
        post :create_contact
        delete :unbookmark
      end
    end
    collection do
      get :search
      get :search_results
      post :search_results
      get :region
      get :state
      get :ministry
    end
  end
  get 'locations/region/:region/state/:state/city/:city' => 'locations#city', :as => :location_city, :constraints => {:city => /.+/}
  get 'locations/region/:region/state/:state/:all' => 'locations#state', :as => :location_state_all
  get 'locations/region/:region/state/:state' => 'locations#state', :as => :location_state
  get 'locations/region/:region/country/:country/city/:city' => 'locations#city', :as => :location_country_city, :constraints => {:city => /.+/}
  get 'locations/region/:region/country/:country/:all' => 'locations#country', :as => :location_country_all
  get 'locations/region/:region/country/:country' => 'locations#country', :as => :location_country
  get 'locations/region/:region/:all' => 'locations#region', :as => :location_region_all
  get 'locations/region/:region' => 'locations#region', :as => :location_region
  get 'locations/ministry/:strategy' => 'locations#ministry', :as => :location_ministry
  get 'locations/:location_id/movements/new/:strategy' => 'movements#new', :as => :location_new_strategy
  delete 'locations/:location_id/movements/:id/remove_contact/:person_id' => 'movements#remove_contact', :as => :movement_remove_contact
  post 'locations/:location_id/movements/:id/add_contact/:person_id' => 'movements#add_contact', :as => :movement_add_contact

  resources :stats do
    collection do
      get :movement
      get :sp
      get :crs
      get :digital
      put :update
      put :create_digital
      put :confirm_digital
    end
  end
  get 'locations/:location_id/movements/:movement_id/stats' => 'stats#movement', :as => :stats_movement

  resources :people do
    collection do
      get :search
      get :search_results
      post :search_results
      get :roles
      get :merge
      post :confirm_merge
      post :do_merge
      get :search_ids
    end
    member do
      get :merge_preview
      get :involvement
    end
  end
  get 'people/roles/:region' => 'people#roles', :as => :people_roles

  get 'reports' => 'reports#create_report', :as => :create_report
  post 'reports/results' => 'reports#do_report', :as => :do_report
  get 'reports/national' => 'reports#national_report', :as => :national_report
  get 'reports/:region' => 'reports#regional_report', :as => :regional_report
  get 'reports/team/:team_id' => 'reports#team_report', :as => :team_report
  get 'reports/location/:location_id' => 'reports#location_report', :as => :location_report

  get 'movement_reports' => 'movement_reports#create_report', :as => :create_movement_report
  post 'movement_reports/results' => 'movement_reports#do_report', :as => :do_movement_report
  get 'movement_reports/movements' => 'movement_reports#movement_report', :as => :movement_report

  get 'home' => 'home#index'
  post 'home/search' => 'home#search', :as => :advanced_search_results
  get 'home/no' => 'home#no'

  get 'monitors/lb' => 'monitors#lb'

  constraint = lambda { |request| request.session['user_id'] and
    User.find(request.session['user_id']).developer? }

  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/logout' => "application#logout", :as => :logout, via: [:get, :post, :delete]

  root :to => 'home#index'

end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_filter :setup, :get_location
  before_filter :get_movement, :except => [:new, :create]
  
  def new
    @movement = Activity.new_movement_for_strategy(@location, params[:strategy])
    if @movement.ActivityID
      redirect_to edit_location_movement_path(@location, @movement)
    end
    populate_select_options(params[:strategy])
    @movement.periodBegin = Time.now.to_date # Initialize date of change to today
  end
  
  def create
    @movement = Activity.new
    @movement.attributes = activity_params
    if @movement.valid?
      @movement.save_create_history(@current_user)
      redirect_to location_path(@location), :notice => "Your request was submitted successfully."
    else
      populate_select_options(@movement.strategy)
      render :new
    end
  end
  
  def edit
    populate_select_options(@movement.strategy)
    @movement.periodBegin = Time.now.to_date # Initialize date of change to today
  end
  
  def update
    @movement.update_attributes_add_history(activity_params, @current_user.userID)
    if @movement.errors.empty?
      redirect_to location_path(@location), :notice => "#{@location.name}, #{@movement.strategy} was updated successfully."
    else
      populate_select_options(@movement.strategy)
      render :edit
    end
  end
  
  def add_contact
    @contact = Person.public.find(params[:person_id])
    if @info_user.can_add_contacts? || @current_user.person == @contact
      if !@movement.contacts.include?(@contact)
        @movement.contacts << @contact
      end
      redirect_to location_path(@location), :notice => "Contact was successfully added."
    else
      redirect_to location_path(@location), :notice => "You do not have permission to add this contact."
    end
  end
  
  def remove_contact
    @contact = Person.find(params[:person_id])
    if @info_user.can_delete_contacts? || @current_user.person == @contact || @movement.team.is_leader?(@current_user.person)
      @movement.contacts.delete(@contact)
      redirect_to location_path(@location), :notice => "Contact was successfully removed."
    else
      redirect_to location_path(@location), :notice => "You do not have permission to remove this contact."
    end
  end
  
  def search_contacts
  end
  
  def search_contacts_results
    @last_name = params[:last_name]
    if !@last_name.blank? && @last_name.size > 1
      @results = Person.public.where("lastName like ?", @last_name + '%').
        includes(:current_address).where(Address.table_name + ".email is not null").references(:current_address).
        order(:lastName).order(:firstName)
      @results = @results - @movement.contacts
      render :search_contacts
    else
      flash.now[:notice] = "You must type at least 2 letters."
      render :search_contacts
    end
  end
  
  def new_contact
    if @info_user.can_add_contacts?
      @person = Person.new
      @person.current_address = Address.new
    else
      redirect_to location_path(@location), :notice => "You do not have permission to add contacts."
    end
  end
  
  def create_contact
    if @info_user.can_add_contacts?
      @person = Person.new
      @person.current_address = Address.new
      @person.current_address.addressType = "current"
      @person.current_address.attributes = current_address_params
      params[:person].delete(:address)
      @person.attributes = person_params
      if @person.current_address.valid? && @person.valid? && !@person.lastName.blank? && !@person.email.blank? && !@person.phone.blank?
        @person.save
        params[:person_id] = @person.personID
        add_contact
      else
        if @person.lastName.blank?
          @person.errors.add(:last_name, "can't be blank")
        end
        if @person.email.blank?
          @person.errors.add(:email, "can't be blank")
        end
        if @person.phone.blank?
          @person.errors.add(:phone, "can't be blank")
        end
        render :new_contact
      end
    else
      redirect_to location_path(@location), :notice => "You do not have permission to add contacts."
    end
  end
  
  def unbookmark
    @bookmark = @movement.get_bookmark_for(current_user)
    if @bookmark
      @bookmark.destroy
      if @bookmark.destroyed?
        redirect_to stats_path, :notice => "Bookmark successfully deleted."
      else
        redirect_to stats_path, :notice => "Unable to delete bookmark."
      end
    else
      redirect_to stats_path
    end
  end
  
  private
  
  def get_location
    @location = TargetArea.find(params[:location_id])
  end
  
  def get_movement
    @movement = Activity.find(params[:id])
    @location = @movement.target_area
  end
  
  def populate_select_options(strategy)
    if strategy == "WS"
      @statuses = Activity.wsn_statuses
    else
      @statuses = Activity.visible_statuses
    end
    if @location.city?
      @teams = Team.where(lane: Strategy.where(city: true).pluck(:abreviation))
    else
      @teams = Team.from_region(@location.region)
    end
    @team_id = @movement.team.id if @movement.team
  end

  def setup
    @menubar = "ministry"
    @submenu = "locations"
    @title = "Infobase - Location Home"
  end

  def activity_params
    params.fetch(:activity).permit(:strategy, :fk_targetAreaID, :status, :periodBegin, :fk_teamID, :url, :facebook)
  end

  def person_params
    params.fetch(:person).permit(:firstName, :lastName, :gender)
  end

  def current_address_params
    params.fetch(:person).fetch(:address).permit(:email, :homePhone)
  end
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/movements/_form.html.erb
<%= f.error_messages %>
<table class='movement_status'>
  <tr>
    <td class='statuses'>
<b>Use the radio buttons to change the status below:</b><br/>
<b>This Ministry Location is ...</b><br/>
<% @statuses.each_key do |status| %>
  <%= f.radio_button :status, status %> <%= f.label :status, Activity.statuses[status].to_s.upcase + " " + Activity.strategies[@movement.strategy].to_s %><br/>
<% end%>
<div id="definition">
  Move your mouse pointer over a<br/>
  capitalized word to see a short explanation.
</div>
    </td>
    <td>
      <div class="infobox" style="display:none"><div class="keyitem"><br/></div></div>
    </td>
  </tr>
</table>
<br/>
<b>What date did this status change take place?</b><br/>
<%= f.date_select :periodBegin, :default => Time.now.to_date %><br/> <!-- TODO: Datepicker? -->
<br/>
<b>Missional Team:</b><br/>
<%= f.select :fk_teamID, options_for_select(@teams.collect {|t| [t.name, t.id]}, @team_id) %><br/>
** Can't find the right Missional Team? Propose one to be entered here: <%= link_to "[New Team]", new_team_path %><br/>
<br/>
<b>URL:</b><%= f.text_field :url %><br/>
<b>Facebook:</b><%= f.text_field :facebook %><br/>
<br/>
<script>
  status_text = {
    "IN": "Inactive – No active Campus Ministry strategy nor potential student leader at this ministry location. No missional team has taken ownership of this location.",
    "PI": "Pioneering – We are actively doing something to start a ministry at this ministry location—prayer, seeking a key contact, evangelism.",
    "KE": "Key Leader – We have found a key leader – student, volunteer, or partner – at this ministry location and are beginning to build a movements.",
    "LA": "Launched – We have  five  people aligned to Win/Build/Send as well as a leader.  These people can be students, faculty, volunteers or a staff member.",
    "MU": "Multiplying – A Movement of 50 or more students involved, or 1% of the student body"
  }
  $("label[for=activity_status]").hover(function() {
      el = $(this).prev();
      $(".keyitem").html(status_text[el.attr("value")]);
      $(".infobox").show();
      $(this).addClass("keyitem_bg");
    }, function() {
      $(this).removeClass("keyitem_bg");
    }
  );
  $("td.statuses").hover(function() {
    }, function() {
      $(".infobox").hide();
    }
  );
</script>

app/views/movements/edit.html.erb
<h2>Edit <%= @location.name %>, <%= Activity.strategies[@movement.strategy] %></h2>
<%= form_for @movement, :url => location_movement_path do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= f.submit "Update Movement" %>
<% end %>

app/views/movements/new.html.erb
<h2>New <%= @location.name %>, <%= Activity.strategies[@movement.strategy] %></h2>
<%= form_for @movement, :url => location_movements_path(@location) do |f| %>
  <%= f.hidden_field :strategy %>
  <%= f.hidden_field :fk_targetAreaID %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= f.submit "Create Movement" %>
<% end %>

app/views/movements/new_contact.html.erb
<h2>Add a Contact for <%= @location.name %>, <%= Activity.strategies[@movement.strategy] %></h2>

<%= form_for @person, :url => movement_create_contact_path do |f| %>
  <% if @person.errors.any? || @person.current_address.errors.any? %>
    <div class="errors">
    <% @person.errors.full_messages.each do |msg| %>
      <div><%= msg.html_safe %></div>
    <% end %>
    <% @person.current_address.errors.full_messages.each do |msg| %>
      <div>
      <%- if msg.is_a?(Hash) && person = msg[:email_exists] -%>
        <%= link_to "Person #{person_gender_email(person)} already exists in the system.  Click here to add them as a reviewer.".html_safe, review_reviewers_url(@review.id, "reviewer[person_id]" => person.id, :close_person_dialog => true), :method => :post, :remote => true %>
      <%- else -%>
        <%= msg %>
      <%- end -%>
      </div>
    <% end %>
    </div>
  <% end %>

  First Name: <%= f.text_field(:firstName) %><br/>
  Last Name: <%= f.text_field(:lastName) %><br/>

  <%= f.fields_for @person.current_address do |af| %>
    Email: <%= af.text_field(:email) %>
  <%- end -%>
  <br/>

  Gender:  <%= f.radio_button :gender, '1' %> Male 
    <%= f.radio_button :gender, '0' %> Female 
  <br/>

  <%= f.fields_for @person.current_address do |af| %>
    Phone: <%= af.text_field(:homePhone) %>
  <%- end -%>
  <br/>
  
  <%= f.submit "Add Contact" %>
<% end %>

app/views/movements/search_contacts.html.erb
<div class="associate">
  <h2>Add a Contact for <%= @location.name %>, <%= Activity.strategies[@movement.strategy] %></h2>
  <%= form_tag movement_search_contacts_results_path(@location, @movement) do %>
    Search by <i>Last Name</i>.  If the person you wish to add is not in the list below, check the spelling of his or her last name and try again.<br/>
    <%= text_field_tag :last_name, @last_name %>
    <%= submit_tag "Search" %>
  <% end %>
  <br/>
  <% if @results %>
    Here is a list of people in the Campus Ministry system.<br/>
    Select which one you want to add as a Movement Contact.<br/>
    <%= form_tag movement_add_contact_path(@location, @movement) do %>
      <%= select_tag :id, options_for_select(@results.collect {|r| [r.full_name + " (" + r.email + ")", r.personID]}) %>
      <%= submit_tag "Add Contact" %>
    <% end %>
    <br/>
    If you still cannot find him or her,
    <%= link_to "click here.", movement_new_contact_path(@location, @movement) %><br/>
  <% end %>
  <%= link_to "Cancel", location_path(@location) %>
</div>