config/routes.rb
require 'sidekiq/web'
Infobase::Application.routes.draw do
  get "gcx_site_users/new"

  get "gcx_site_users/create"

  resources :gcx_sites
  resources :gcx_site_users

  namespace :api, defaults: {format: 'json'} do
    api_version(module: 'V1', header: {name: 'API-VERSION', value: 'v1'}, parameter: {name: "version", value: 'v1'}, path: {value: 'v1'}) do
      resources :ministries
      resources :regions
      resources :teams do
        collection do
          post :search # This is needed for searches with lots of parameters
        end
      end
      resources :target_areas
      resources :users
      resources :activities
      resources :strategies
      resources :people

      resources :statistics do
        collection do
          get :activity
          get :sp_evangelism_combined
          post :collate_stats
          post :collate_stats_intervals
          post :movement_stages
        end
      end

      resources :people do
        collection do
          get :is_staff
          post :is_staff
        end
      end
    end
  end

  resources :infobase_report_rows

  resources :teams do
    collection do
      get :search
      get :search_results
      post :search_results
      get :region
      get :state
      get :ministry
    end
    member do
      post :add_member
      delete :remove_member
      get :search_members
      post :search_members_results
      get :new_member
      post :create_member
      post :add_leader
      post :remove_leader
    end
  end
  get 'teams/validate/:name' => 'teams#validate_name'
  get 'locations/validate/:name' => 'locations#validate_name'
  get 'teams/region/:region/state/:state/city/:city' => 'teams#city', :as => :team_city, :constraints => {:city => /.+/}
  get 'teams/region/:region/state/:state/:all' => 'teams#state', :as => :team_state_all
  get 'teams/region/:region/state/:state' => 'teams#state', :as => :team_state
  get 'teams/region/:region/country/:country/city/:city' => 'teams#city', :as => :team_country_city, :constraints => {:city => /.+/}
  get 'teams/region/:region/country/:country/:all' => 'teams#country', :as => :team_country_all
  get 'teams/region/:region/country/:country' => 'teams#country', :as => :team_country
  get 'teams/region/:region/:all' => 'teams#region', :as => :team_region_all
  get 'teams/region/:region' => 'teams#region', :as => :team_region
  get 'teams/ministry/:strategy' => 'teams#ministry', :as => :team_ministry
  post 'teams/:id/add_member/:person_id' => 'teams#add_member', :as => :team_add_member
  delete 'teams/:id/remove_member/:person_id' => 'teams#remove_member', :as => :team_remove_member
  post 'teams/:id/add_leader/:person_id' => 'teams#add_leader', :as => :team_add_leader
  post 'teams/:id/remove_leader/:person_id' => 'teams#remove_leader', :as => :team_remove_leader

  resources :locations do
    resources :movements do
      member do
        post :add_contact
        delete :remove_contact
        get :search_contacts
        post :search_contacts_results
        get :new_contact
        post :create_contact
        delete :unbookmark
      end
    end
    collection do
      get :search
      get :search_results
      post :search_results
      get :region
      get :state
      get :ministry
    end
  end
  get 'locations/region/:region/state/:state/city/:city' => 'locations#city', :as => :location_city, :constraints => {:city => /.+/}
  get 'locations/region/:region/state/:state/:all' => 'locations#state', :as => :location_state_all
  get 'locations/region/:region/state/:state' => 'locations#state', :as => :location_state
  get 'locations/region/:region/country/:country/city/:city' => 'locations#city', :as => :location_country_city, :constraints => {:city => /.+/}
  get 'locations/region/:region/country/:country/:all' => 'locations#country', :as => :location_country_all
  get 'locations/region/:region/country/:country' => 'locations#country', :as => :location_country
  get 'locations/region/:region/:all' => 'locations#region', :as => :location_region_all
  get 'locations/region/:region' => 'locations#region', :as => :location_region
  get 'locations/ministry/:strategy' => 'locations#ministry', :as => :location_ministry
  get 'locations/:location_id/movements/new/:strategy' => 'movements#new', :as => :location_new_strategy
  delete 'locations/:location_id/movements/:id/remove_contact/:person_id' => 'movements#remove_contact', :as => :movement_remove_contact
  post 'locations/:location_id/movements/:id/add_contact/:person_id' => 'movements#add_contact', :as => :movement_add_contact

  resources :stats do
    collection do
      get :movement
      get :sp
      get :crs
      get :digital
      put :update
      put :create_digital
      put :confirm_digital
    end
  end
  get 'locations/:location_id/movements/:movement_id/stats' => 'stats#movement', :as => :stats_movement

  resources :people do
    collection do
      get :search
      get :search_results
      post :search_results
      get :roles
      get :merge
      post :confirm_merge
      post :do_merge
      get :search_ids
    end
    member do
      get :merge_preview
      get :involvement
    end
  end
  get 'people/roles/:region' => 'people#roles', :as => :people_roles

  get 'reports' => 'reports#create_report', :as => :create_report
  post 'reports/results' => 'reports#do_report', :as => :do_report
  get 'reports/national' => 'reports#national_report', :as => :national_report
  get 'reports/:region' => 'reports#regional_report', :as => :regional_report
  get 'reports/team/:team_id' => 'reports#team_report', :as => :team_report
  get 'reports/location/:location_id' => 'reports#location_report', :as => :location_report

  get 'movement_reports' => 'movement_reports#create_report', :as => :create_movement_report
  post 'movement_reports/results' => 'movement_reports#do_report', :as => :do_movement_report
  get 'movement_reports/movements' => 'movement_reports#movement_report', :as => :movement_report

  get 'home' => 'home#index'
  post 'home/search' => 'home#search', :as => :advanced_search_results
  get 'home/no' => 'home#no'

  get 'monitors/lb' => 'monitors#lb'

  constraint = lambda { |request| request.session['user_id'] and
    User.find(request.session['user_id']).developer? }

  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/logout' => "application#logout", :as => :logout, via: [:get, :post, :delete]

  root :to => 'home#index'

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :setup
  before_filter :get_location, :only => [:show, :edit, :update]
  before_filter :search_options, :only => [:new, :edit, :search]
  before_filter :populate_breadcrumbs, :only => [:show, :edit]
  
  def index
    @regions = Region.standard_regions
    @strategies = Activity.visible_strategies
    @city_strategies = Activity.city_strategies
  end
  
  def show
    if @location.blank? || @location.type == "Event"
      redirect_to locations_path
      return
    end
    @reports_link = location_report_path(@location, {:event_type => "campus", :from => last_august(), :to => Date.today.to_s, :strategies => Activity.visible_strategies.keys})
    @open_strategies = Activity.determine_open_strategies(@location)
    @title = "Infobase - " + @location.name
  end
  
  def new
    @location = TargetArea.new(target_area_params)
    @title = "Infobase - Propose New Location"
  end
  
  def create
    @location = TargetArea.new(target_area_params)
    if @location.valid?
      if @info_user.can_create_locations?
        @location.save!
        redirect_to location_path(@location), :notice => "Location was created successfully."
      else
        host = request.host_with_port
        ProposeMailer.propose_location(@location, current_user.person, host).deliver
        redirect_to locations_path, :notice => "Your proposed location has been submitted for approval. This manual process may take a few days.."
      end
    else
      search_options
      @name_options = {}
      render :new
      @title = "Infobase - Propose New Location"
    end
  end
  
  def edit
    @name_options = {:readonly => true}
    @title = "Infobase - Edit " + @location.name
  end
  
  def update
    @location.update_attributes(target_area_params)
    if @location.errors.empty?
      redirect_to location_path(@location), :notice => "#{@location.name} was updated successfully."
    else
      search_options
      populate_breadcrumbs
      @name_options = {:readonly => true}
      render :edit
      @title = "Infobase - Edit" + @location.name
    end
  end
  
  def search
    @title = "Infobase - Location Search"
  end
  
  def validate_name
    data = TargetArea.find_by_name(params[:name].strip)
    if data.present?
      response = data.id == params[:id].to_i ? 2 : 1 
    else
      response = 0 
    end
    # 0 - Available
    # 1 - Used by others
    # 2 - Same as currentons
    render :text => response
  end
  
  def region
    if params[:all]
      perform_search
    else
      @states = TargetArea.open_school.select("distinct state").where("region = ?", @region).where("state is not null and state != ''").order(:state)
      @countries = TargetArea.open_school.select("distinct country").where("region = ?", @region).where("country is not null and country != ''").order(:country)
      @title = "Infobase - Locations in " + Region.full_name(@region)
    end
  end
  
  def state
    if State.states[@state]
      if params[:all]
        perform_search
      else
        @cities = TargetArea.open_school.select("distinct city").where("region = ?", @region).where("state = ?", @state).where("city is not null and city != ''").order(:city)
        @title = "Infobase - Locations in " + State.states[@state]
      end
    else # invalid state
      redirect_to location_region_path(@region)
    end
  end
  
  def country
    if params[:all]
      perform_search
    else
      @region = params[:region]
      @country = params[:country]
      @cities = TargetArea.open_school.select("distinct city").where("region = ?", @region).where("country = ?", @country).where("city is not null and city != ''").order(:city)
      @title = "Infobase - Locations in " + Country.full_name(@country).to_s
    end
  end
  
  def city
    perform_search
  end
  
  def ministry
    params[:strategies] = [params[:strategy]]
    search_results
    render :search_results
  end
  
  def search_results
    if params[:cru_city].blank? && params[:namecity].blank? && params[:name].blank? && params[:city].blank? && params[:state].blank? && params[:country].blank? && params[:regions].blank? && params[:strategies].blank?
      redirect_to search_locations_path, :notice => "You must fill in at least one search option."
    end
    if (!params[:name].blank? && params[:name].size < 2) || (!params[:namecity].blank? && params[:namecity].size < 2)
      redirect_to search_locations_path, :notice => "You must fill in at least two letters of the name."
    end
    
    @locations = TargetArea.open_school.includes(:activities).order(:name)
    if !params[:namecity].blank?
      @locations = @locations.where("name like ? OR city like ? OR infoUrl like ?", "%#{params[:namecity]}%", "#{params[:namecity]}%", "%#{params[:namecity]}%")
    end
    if !params[:name].blank?
      @locations = @locations.where("name like ?", "%#{params[:name]}%")
    end
    if !params[:city].blank?
      @locations = @locations.where("city like ?", "#{params[:city]}%")
    end
    if !params[:state].blank?
      @locations = @locations.where("state = ?", params[:state])
    end
    if !params[:country].blank?
      @locations = @locations.where("country = ?", params[:country])
    end
    if !params[:regions].blank?
      @locations = @locations.where("region IN (?)", params[:regions])
    end
    if !params[:cru_city].blank?
      @locations = @locations.where("type = 'City'")
    end
    if !params[:strategies].blank?
      @locations = @locations.where(Activity.table_name + ".strategy IN (?)", params[:strategies]).references(:activities)
    end
    @title = "Infobase - Search Results"
  end
  
  private
    def setup
      @menubar = "ministry"
      @submenu = "locations"
      @region = params[:region]
      @state = params[:state]
      @country = params[:country]
      @city = params[:city]
      @title = "Infobase - Location Home"
    end
    
    def get_location
      begin
        @location = TargetArea.find(params[:id])
      rescue
        @location = nil
      end
    end
    
    def populate_breadcrumbs
      if @location
        @region = @location.region
        @state = @location.state unless @location.country != "USA"
        @country = @location.country unless @location.country == "USA" || @location.country.blank?
        @city = @location.city
      end
    end
    
    def perform_search
      params[:regions] = [params[:region]]
      search_results
      render :search_results
    end

    def target_area_params
      params.fetch(:target_area).permit(:region, :name, :altName, :abbrv, :address1, :address2, :city, :state, :zip, :country, :url, :infoUrl, :enrollment, :urlToLogo, :monthSchoolStarts, :monthSchoolStops, :isSecure, :type, :note, :gate) if params.has_key?(:target_area)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= f.error_messages %>
(* = required field)
		</td>
	</tr>

<table id="styled_form_table">
  <tr>
    <td id="label_column"><%= f.label :type, "*Location Type:" %></td>
    <td id="field_column">
      <%= f.select :type, options_for_select(['College','High School','City'], @location.type) %>
    </td>
  </tr>
  <tr>
    <td id="label_column"><%= f.label :region, "Region:" %></td>
    <td id="field_column">
      <%= f.select :region, options_for_select([['','']] + @regions.collect {|r| [r.name, r.region]}, @location.region) %>
    </td>
  </tr>
	<tr>
		<td><%= f.label :name, "*Location Name:" %></td>
		<td>
			<%= hidden_field_tag :location_id, params[:id] %>
			<%= f.text_field :name, :autocomplete => 'off' %>
			<span id="target_area_name_result"></span>
			<%= spinner('target_area_name') %>
			
		</td>
	</tr>
	<tr>
		<td><%= f.label :altName, "Alternate Name:" %></td>
		<td>
			<%= f.text_field :altName %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :abbrv, "Abbreviation:" %></td>
		<td>
			<%= f.text_field :abbrv %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :address1, "Address 1:" %></td>
		<td>
			<%= f.text_field :address1 %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :address2, "Address 2:" %></td>
		<td>
			<%= f.text_field :address2 %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :city, "*City:" %></td>
		<td>
			<%= f.text_field :city %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :state, "State:" %></td>
		<td>
			<%= f.select :state, options_for_select(@states, @location.state) %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :zip, "Zip:" %></td>
		<td>
			<%= f.text_field :zip %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :country, "*Country:" %></td>
		<td>
			<%= f.select :country, options_for_select(@countries, @location.country) %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :url, "Local Level Ministry URL:" %></td>
		<td>
			<%= f.text_field :url %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :infoUrl, "Other School Website URL:" %></td>
		<td>
			<%= f.text_field :infoUrl %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :enrollment, "Population/Enrollment/Scope:" %></td>
		<td>
			<%= f.text_field :enrollment, maxlength: 9 %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :urlToLogo, "Ministry Location Logo URL:" %></td>
		<td>
			<%= f.text_field :urlToLogo %>
		</td>
	</tr>
	<tr>
		<td><%= f.label :monthSchoolStarts, "Month and Day School Starts:" %></td>
		<td>
			<%= f.text_field :monthSchoolStarts %> (i.e. AUG30)
		</td>
	</tr>
	<tr>
		<td><%= f.label :monthSchoolStops, "Month and Day School Ends:" %></td>
		<td>
			<%= f.text_field :monthSchoolStops %> (i.e. MAY06)
		</td>
	</tr>
	<tr>
		<td><%= f.label :isSemester, "Semester System?" %></td>
		<td>
			<%= f.radio_button :isSemester, "T" %>Yes
			<%= f.radio_button :isSemester, "F" %>No
		</td>
	</tr>
	<tr>
		<td><%= f.label :isSecure, "*Is this Ministry Location secure?" %></td>
		<td>
			<%= f.radio_button :isSecure, "T" %>Yes
      <%= f.radio_button :isSecure, "F" %>No
		</td>
	</tr>
	<tr>
		<td><%= f.label :note, "Note:", :style => "vertical-align:top;" %></td>
		<td>
			<%= f.text_area :note %>
		</td>
	</tr>
</table>

app/views/locations/country.html.erb
<h2><%= Region.full_name(@region).to_s + ", " + Country.full_name(@country).to_s %></h2>
<b>Look for your Location by selecting the City below:</b><br/>
<% @cities.each do |ta| %>
  <%= link_to ta.city, location_country_city_path(@region, @country, ta.city) %><br/>
<% end %>

app/views/locations/edit.html.erb
<h2>Edit <%= @location.name %></h2>
<%= form_for @location, :url => location_path(@location) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= f.submit "Update Location" %>
<% end %>

app/views/locations/index.html.erb
<h2>Welcome to the Location Home page.</h2>
<b>Look for your Location by selecting the Region below:</b>
<br/>
<table>
  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td>
          <%= link_to region.name, location_region_path(region.abbrv) %>
          <%= link_to "(all)", location_region_all_path(region.abbrv, "all") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<b>Or search by Strategy:</b>
<br/>
<table>
  <tbody>
    <% @strategies.each_key do |strategy| %>
      <tr>
        <td><%= link_to @strategies[strategy], location_ministry_path(strategy) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<b>Or search by City Gate:</b>
<table>
  <tbody>
  <tr>
    <td><%= link_to 'All Cities', search_results_locations_path(cru_city: true) %></td>
  </tr>
  <% @city_strategies.each_key do |strategy| %>
    <tr>
      <td><%= link_to @city_strategies[strategy], location_ministry_path(strategy) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/locations/new.html.erb
<h2>Propose New Location</h2>
<%= form_for @location, :url => locations_path do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= f.submit "Submit New Location", :id => "location_submit_button" %>
<% end %>

app/views/locations/region.html.erb
<h2><%= Region.full_name(@region) %></h2>
<b>Look for your Location by selecting the State below:</b><br/>
<% @states.each do |ta| %>
  <%= link_to State.states[ta.state], location_state_path(@region, ta.state) %>
  <%= link_to "(all)", location_state_all_path(@region, ta.state, "all") %><br/>
<% end %>
<br/><br/>
<b>Or look for your Location in the Countries below:</b><br/>
<% @countries.each do |ta| %>
  <%= link_to Country.full_name(ta.country).to_s, location_country_path(@region, ta.country) %>
  <%= link_to "(all)", location_country_all_path(@region, ta.country, "all") %><br/>
<% end %>

app/views/locations/search.html.erb
<%= render :partial => 'home/search_form', :locals => { :search_type => "locations" } %>

app/views/locations/search_results.html.erb
<h2>Search Results</h2>
<table>
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.name, location_path(location) %></td>
        <td>
          <%= location.city %><%= "," if !location.city.blank? %>
          <%= location.state %><%= "," if !location.state.blank? %>
          <%= Country.full_name(location.country) %><%= "," if !location.country.blank? %>
          <%= Region.full_name(location.region()) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/locations/show.html.erb
<h1>
  <%= @location.name %>&nbsp;&nbsp;
  <%= link_to "", edit_location_path(@location), :class => "editfield" %>
  <%= link_to "(edit)", edit_location_path(@location), :class => "edittext" %>
</h1>

<h3 class="indented">
  Details about this Location
  &nbsp;&nbsp;<%= link_to "View Report", @reports_link %>
</h3>

<div class="strategy">
  <div class="details">
    <div class="thecolumn">
      <div class="field">
        <label>Address:</label>
        <div class="box">
          <%= @location.address1 %>&nbsp;<%= @location.address2 %><br>
          <%= @location.city %><%= (@location.state.blank? || @location.city.blank? ? "" : ",") %>
          <%= @location.state %><br>
          <%= @location.zip %><%= (@location.country.blank? || @location.zip.blank? ? "" : ",") %>
          <%= @location.country %><br>
        </div>
      </div>

      <% unless @location.city? %>
        <div class="field">
          <label>Region:</label>
          <%= Region.full_name(@location.region) %>
        </div>
        <br/>
      <% end %>

      <div class="field">
        <label>Phone:</label>
        <%= @location.phone %>
      </div>
      <br/>

      <div class="field">
        <label>Email:</label>
        <%= @location.email %>
      </div>
    </div>

    <div class="thecolumn">
      <div class="field">
        <label>Enrollment:</label>
        <%= @location.enrollment %>
      </div>
      <br/>

      <div class="field">
        <label>Semester?</label>
        <%= @location.is_semester? %>
      </div>
      <br/>

      <div class="field">
        <label>School Year:</label>
        <%= @location.monthSchoolStarts %> - <%= @location.monthSchoolStops %>
      </div>
      <br/>

      <div class="field">
        <label>School Website:</label>
        <%= link_to display_website(@location.infoUrl), display_website(@location.infoUrl) %>
      </div>
      <br/>

      <% if !@location.urlToLogo.blank? %>
        <div class="field">
          <%= image_tag display_website(@location.urlToLogo), :alt => "" %>
        </div>
      <% end %>
    </div>
    <div class="clear"></div>
  </div>
</div>

<% @location.activities.each do |activity| %>
  <div class="strategy">
    <h3>
      <%= Activity.all_strategies[activity.strategy] %>&nbsp;&nbsp;
      <%= link_to "", edit_location_movement_path(@location, activity), :class => "editfield" %>
      <%= link_to "(edit)", edit_location_movement_path(@location, activity), :class => "edittext" %>
    </h3>
    <br/>
    <div class="details">
      <div class="thecolumn" style="float: left;">
        <div class="field">
          <label>Status:</label>
          <%= link_to Activity.statuses[activity.status], edit_location_movement_path(@location, activity) %>
        </div>
        <br/>

        <div class="field">
          <label>Contacts:</label>
          <div class="box">
            <% activity.contacts.each do |contact| %>
              <% if contact.isSecure.to_s == 'T' %>
                <img src="/assets/icons/flag_yellow.png" title="Secure Contact" />
              <% end %>
              <%= link_to contact.full_name, person_path(contact) %>
              <% if @info_user.can_delete_contacts? || current_user.person.personID == contact.personID || activity.team.is_leader?(@current_user.person) %>
                <%= link_to "", movement_remove_contact_path(@location, activity, contact.personID.to_s), :method => :delete, :data => { :confirm => "Are you sure?" }, :class => "deletefield" %>
              <% end %>
              <br/>
            <% end %>
            <% if !activity.contacts.include?(@current_user.person) %>
              <%= link_to "Become a Contact for this Movement", movement_add_contact_path(@location, activity, @current_user.person.personID.to_s), :method => :post %><br/>
            <% end %>
            <% if @info_user.can_add_contacts? %>
              <%= link_to "Add Contact", search_contacts_location_movement_path(@location, activity) %>
            <% end %>
          </div>
        </div>

        <div class="clear"></div>
      </div>

      <div class="thecolumn" style="float: right;">
        <div class="field">
          <label>Missional Team:</label>
          <%= link_to activity.team.name, team_path(activity.team) if activity.team %>
        </div>
        <br/>

        <div class="field">
          <label>Size:</label>
          <%= activity_size(activity) %>
          (<%= link_to "Enter Movement Indicators", stats_movement_path(@location, activity) %>)
        </div>
        <br/>

        <div class="field">
          <label>Facebook:</label>
          <%= link_to display_website(activity.facebook), display_website(activity.facebook) if activity.facebook.present? %>
        </div>
        <br/>
        <% if activity.url.present? && activity.gcx_site.blank? %>
          <div class="field">
            <label>Website:</label>
            <%= link_to display_website(activity.url), display_website(activity.url) if activity.url.present? %>
          </div>
          <br />
        <% end %>
        <% if activity.gcx_site.present? %>
          <div class="field">
            <label>GCX Site:</label>
            <%= link_to("#{Rails.configuration.gcx_url}/#{activity.gcx_site}", "#{Rails.configuration.gcx_url}/#{activity.gcx_site}", target: '_blank') %>
          </div>      <br />
          <div class="field">
            <label>Manage GCX Site:</label>
            <%= link_to("#{Rails.configuration.gcx_url}/#{activity.gcx_site}/wp-admin", "#{Rails.configuration.gcx_url}/#{activity.gcx_site}/wp-admin", target: '_blank') %>
          </div>
        <% else %>
          <div class="field">
            <label>GCX Site:</label>
            <%= link_to('Click here to set up a website for this movement (made with GCX)', new_gcx_site_path(activity_id: activity.id)) %>
          </div>
        <% end %>
        <div class="clear"></div>
      </div>

      <div class="clear"></div>
    </div><!-- end detail -->
  </div><!-- end strategy -->
<% end %>

<% if @location.city? %>
  <% Activity.city_strategies.each do |abbv, strategy| %>
    <%= link_to "Add " + strategy, location_new_strategy_path(@location, abbv) %><br/>
  <% end %>
<% else %>
  <% @open_strategies.each do |strategy| %>
    <%= link_to "Add " + Activity.strategies[strategy], location_new_strategy_path(@location, strategy) %><br/>
  <% end %>
<% end %>

app/views/locations/state.html.erb
<h2><%= Region.full_name(@region) + ", " + State.states[@state] %></h2>
<b>Look for your Location by selecting the City below:</b><br/>
<% @cities.each do |ta| %>
  <%= link_to ta.city, location_city_path(@region, @state, ta.city) %><br/>
<% end %>